name: 'feature'
description: '기능 구현 및 수정 작업'
labels: 'feature'
body:
  - type: textarea
    attributes:
      label: 작업 설명
      description: 작업에 대한 설명을 작성해 주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 작업 목록
      description: 작업 목록을 작성해 주세요.

  - type: textarea
    attributes:
      label: 기타
      placeholder: 브랜치 생성 시 ${issue 타입}/${issue 번호}-${설명} 형식으로 지정해주세요! ex) feature/1-UI-Button
